#!/usr/bin/env bash
# Installs nginx and creates a webpage with string "Holberton School"

sudo apt-get update
sudo apt-get install -y nginx

# add a file called index.html to the folder /var/www/html/default
# by echoing the text "Holberton School" to the index.html file

sudo echo "Holberton School" > /var/www/html/index.html
sudo echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	index index.html;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}
}" > /etc/nginx/sites-available/default

sudo systemctl restart nginx
