#!/usr/bin/env bash
# Installs nginx and redirects domain.tech/redirect_me to a random kitty video

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" > /var/www/html/index.html
sudo sed 's/^\tserver_name.*/\trewrite ^\/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default > /etc/nginx/sites-available/default
sudo service nginx restart
