#!/usr/bin/env bash
# This script pings a specific port
# fed by the terminal five times
# Usage: ./5-is_the_host_on_the_network [IP Address]
if [ "$#" -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi
ping -c 5 "$1"
