#!/usr/bin/env bash

# Push the PID to the given location
sudo touch /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid

# Setup Trap Definitions
trap 'echo I hate the kill command && sudo rm -rf /var/run/holbertonscript.pid && exit' SIGTERM
trap 'sudo rm -rf /var/run/holbertonscript.pid; exit' SIGQUIT
trap "echo Y U no love me?!" SIGINT

i=0
while [ $i -eq 0 ];
do
	echo "To infinity and beyond"
done
