#!/usr/bin/env bash
# Blocks any SIGTERMS delivered to the
# script. When SIGTERM's pushed onto the
# script, the function echo's "I am invincible!!!"

i=0
while [ $i -eq 0 ];
do
	trap "echo 'I am invincible!!!'" SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
