#!/usr/bin/env bash
# Reads the /etc/passwd file, extracts and prints
# the username, UID, and Home directory path for
# the user

FILE=/etc/passwd

while IFS= read -r lines
do
	echo $lines | cut -d ':' -f 1,3,6
done < "$FILE"
