#!/usr/bin/env bash
# Prints out "Holberton School" using the while loop

i=0

# Notes : While the count $i is less than (-lt), run the loop
while [ $i -lt 10 ]
do
	echo "Holberton School"
	((i++))
done
