#!/usr/bin/env bash
# Prints out "Holberton School" 10 times with
# the help of the until loop

i=1

# Notes: Until i is less than (-lt) 'do' the following
until [ $i -gt 10 ]
do
	echo "Holberton School"
	((i++))
done
