#!/usr/bin/env bash
# Prints out Holberton School 10 times. Howevever,
# it replaces the "Holberton School" call with
# "good luck" and "bad luck" on the fourth and eighth
# call

i=1

while [ $i -le 10 ];
do
	if [ $i == 4 ]; then
		echo "bad luck"
	elif [ $i == 8 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i++))
done
