#!/usr/bin/env bash
# Prints out numbers from 1 to 20. On the
# 4th, 9th and 17th iteration, displays
# "bad luck from China/Japan/Italy", respectively

i=1

while [ $i -le 20 ];
do
	echo $i
	case $i in

		4)
			echo "bad luck from China"
			;;

		9)
			echo "bad luck from Japan"
			;;

		17)
			echo "bad luck from Italy"
			;;

	esac
	((i++))
done
