#!/usr/bin/env bash
# Lesson of the day: Always check your error logs
sudo chown -R nginx:nginx /etc/nginx/
sudo chmod 0700 nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
