#!/usr/bin/env bash
# Lesson of the day: Always check your error logs
sudo chown -R nginx:nginx /etc/nginx/
sudo chmod 0700 nginx.conf
sed 's/80/8080/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
